Dont use flags for meta chars
theseion/crs-toolchain pull request #34
Opened 2022-11-06 09:36 UTC by theseion

2022-11-07 19:34 UTC, fzipi requested changes
Are we indenting using 8 spaces instead of 4, right?

2022-11-07 19:34 UTC, fzipi commented on regex/operators/assembler.go
> +// `^` to `(?m:^)`, `$` to (?m:$)`.
```suggestion
// The Go regexp/syntax library will convert:
// - a dot (`.`) into `(?-s:.)`
// - a caret (`^`) into `(?m:^)`
// - a dollar (`$`) into (?m:$)`
```

2022-11-07 19:34 UTC, fzipi commented on regex/operators/assembler.go
> +}
Why not add the patterns as a `map[string]string` and range over it?

2022-11-08 07:23 UTC, theseion commented
Actually, I'm using tabs, which is what `gofmt` uses. In my VS Code it uses 8 spaces to represent the width of one tab character, but that's only visuals. Where are you seeing spaces?

2022-11-09 17:32 UTC, theseion commented
ping

2022-11-09 20:01 UTC, merged